I18N: Add Catalan language and improve Spanish translations
OnionUI/Onion pull request #1151
Opened 2023-09-13 19:12 UTC by sandrasgg

- Add missing Spanish translations
- Fix/Improve some Spanish translations
- Add Catalan language

2023-09-19 20:27 UTC, XK9274 approved these changes
Catalan looks good:

<details>

```json
    "lang": "Català",
    "0": "Expert",
    "1": "Favorites",
    "2": "Games",
    "3": "ARCADE",
    "4": "NEOGEO",
    "5": "FC",
    "6": "SFC",
    "7": "GB",
    "8": "GBA",
    "9": "MD",
    "10": "GPSP",
    "11": "SMS",
    "12": "PS",
    "13": "PCE",
    "14": "OTHERS",
    "15": "Settings",
    "16": "GAME INFO",
    "17": "DEVICE INFO",
    "18": "Recent",
    "19": "ARCHIVE",
    "20": "ADC INFO",
    "21": "EncDec Test",
    "22": "Button Reassignment",
    "23": "Change Language",
    "24": "Volume",
    "25": "Menu Sound",
    "26": "Brightness",
    "27": "Refresh ROMs",
    "28": "Factory Reset",
    "29": "Flash Mode",
    "30": "About Device",
    "31": "Hardware Test",
    "32": "ADC Info",
    "33": "Status:",
    "34": "Delay:",
    "35": "OK Ratio:",
    "36": "Error Ratio:",
    "37": "STOPPED",
    "38": "RUNNING",
    "39": "ADC:",
    "40": "Loading",
    "41": "OTG",
    "42": "Disconnected",
    "43": "Error",
    "44": "Added to Favorites",
    "45": "CANCEL",
    "46": "OK",
    "47": "Seconds",
    "48": "To",
    "49": "Playlist",
    "50": "Delete List",
    "51": "Load",
    "52": "Delete from List",
    "53": "Erasing Game Data",
    "54": "Refresh All ROMs",
    "55": "Add to Favorites",
    "56": "Refresh",
    "57": "Update System?",
    "58": "Low SD Space\n%dM remaining",
    "59": "Model Number",
    "60": "Serial Number",
    "61": "Firmware Version",
    "62": "CPU Frequency",
    "63": "%dMHz",
    "64": "RAM",
    "65": "%dMB",
    "66": "Used/Total Storage",
    "67": "Reset Settings",
    "68": "Reset System Settings?\nSD card contents\nwill not be deleted.",
    "69": "Update ROMs on SD card",
    "70": "Reset",
    "71": "Default",
    "72": "Rotation90",
    "73": "Map3",
    "74": "Unknown",
    "75": "LOADING",
    "76": "Loading",
    "77": "Clear Recent List?",
    "78": "Note: SD card contents\nwill not be deleted.",
    "79": "Clear Favorites List?",
    "80": "Note: SD card contents\nwill not be deleted.",
    "81": "Delete from Favorites?",
    "82": "Note: SD card contents\nwill not be deleted.",
    "83": "Scanning...",
    "84": "GAME INFO",
    "85": "Create Cache",
    "86": "Close",
    "87": "Closing in %d seconds...",
    "88": "SELECT",
    "89": "BACK",
    "90": "NAVIGATE",
    "91": "MENU",
    "92": "Continue",
    "93": "Save",
    "94": "Load",
    "95": "Volume",
    "96": "Exit to Menu",
    "97": "Status %d/%d",
    "98": "No Status",
    "99": "No Thumbnail",
    "100": "Load Failed",
    "101": "Save Failed",
    "102": "Slot %d Saved",
    "103": "Fullscreen",
    "104": "Turn On",
    "105": "Turn Off",
    "106": "Advanced",
    "107": "Applications",
    "108": "Are you sure you want to\nturn off the device?",
    "109": "IO Test",
    "110": "Button Assignment",
    "111": "EXIT",
    "112": "SAVE AND EXIT",
    "113": "%d Later",
    "114": "Exit",
    "115": "Suspend",
    "116": "Delete game from SD card?",
    "117": "Confirm you want to delete this\ngame from the SD card.",
    "118": "Screen",
    "119": "Brightness",
    "120": "Hue",
    "121": "Saturation",
    "122": "Contrast",
    "123": "\n\nScreen settings saved!\nDo not restart the device.\n\n",
    "124": "Apply Changes",
    "125": "Themes",
    "126": "Font Size",
    "127": "Default",
    "128": "Delete",
    "129": "Audio Repair",
    "130": "Repairs",
    "131": "WIFI",
    "132": "ACTIVITY",
    "133": "Connect",
    "134": "Hotspot",
    "135": "SSID",
    "136": "Password",
    "137": "Bluetooth",
    "138": "Netplay",
    "139": "Bluetooth System Restore",
    "140": "Scanning",
    "141": "No Device Found",
    "142": "Bluetooth Not Ready",
    "143": "Put ROMs in the following directory",
    "144": "Restore Bluetooth",
    "145": "Hotspot Enabled",
    "146": "CPU Frequency",
    "147": "Connected",
    "148": "My Device",
    "149": "Another Device",
    "150": "Information",
    "151": "Enter SSID",
    "152": "Enter Password",
    "153": "Search",
    "154": "Connection Error\nCheck Password\nOr restart the router.",
    "155": "Website",
    "300": "NEXT",
    "301": "CONTINUE"
}
```

</details>

Spanish changes look good:

<details>

```json
	"lang": "Spanish (Español)",
	"0": "Expert",
	"1": "Favorites",
	"2": "Consoles",
	"3": "ARCADE",
	"4": "NEOGEO",
	"5": "FC",
	"6": "SFC",
	"7": "GB",
	"8": "GBA",
	"9": "MD",
	"10": "GPSP",
	"11": "SMS",
	"12": "PS",
	"13": "PCE",
	"14": "OTHERS",
	"15": "Settings",
	"16": "GAME INFO",
	"17": "CONSOLE INFO",
	"18": "Recent",
	"19": "FILE",
	"20": "ADC INFO",
	"21": "EncDec Test",
	"22": "Button Mapping",
	"23": "Language",
	"24": "Volume",
	"25": "BGM Volume",
	"26": "Brightness",
	"27": "Update Roms",
	"28": "Factory Reset",
	"29": "Flashing Mode",
	"30": "Device Information",
	"31": "Hardware Test",
	"32": "ADC Info",
	"33": "Status:",
	"34": "Delay:",
	"35": "OK Rate:",
	"36": "Failure Rate:",
	"37": "STOPPED",
	"38": "RUNNING",
	"39": "ADC:",
	"40": "Loading",
	"41": "OTG",
	"42": "Disconnected",
	"43": "Error",
	"44": "favorites",
	"45": "cancel",
	"46": "OK",
	"47": "seconds",
	"48": "in",
	"49": "Recent List",
	"50": "Clear",
	"51": "Open",
	"52": "Delete",
	"53": "Refresh",
	"54": "Refresh Roms",
	"55": "Add as favorite",
	"56": "Update",
	"57": "Update firmware?",
	"58": "Low SD Capacity\n%dM remaining",
	"59": "Model number",
	"60": "Serial number",
	"61": "Version",
	"62": "CPU",
	"63": "%dMHz",
	"64": "RAM",
	"65": "%dM",
	"66": "SD Card",
	"67": "Restore entire system",
	"68": "Restore entire system\nSD content\nwill not be deleted",
	"69": "Update roms on SD card",
	"70": "Restore",
	"71": "default",
	"72": "rotation90",
	"73": "map3",
	"74": "Location",
	"75": "LOADING",
	"76": "Loading",
	"77": "Clear list",
	"78": "Clear recent\nSD content\nwill not be deleted",
	"79": "Clear favorites",
	"80": "Clear games from this list\nSD content\nwill not be deleted",
	"81": "Remove from favorites",
	"82": "Remove game from this list\nSD content\nwill not be deleted",
	"83": "Scan games",
	"84": "GAME INFO",
	"85": "Create cache",
	"86": "Turn off",
	"87": "Turn off in %d seconds",
	"88": "OPEN",
	"89": "BACK",
	"90": "NAVIGATE",
	"91": "MENU",
	"92": "Continue",
	"93": "Save",
	"94": "Load",
	"95": "Volume",
	"96": "Exit game",
	"97": "Save %d/%d",
	"98": "Empty",
	"99": "No image",
	"100": "Failed to load",
	"101": "Failed to save",
	"102": "Slot %d saved",
	"103": "Full screen",
	"104": "Turn on",
	"105": "Turn off",
	"106": "Native Menu",
	"107": "Application",
	"108": "Turn off the device?",
	"109": "IO Test",
	"110": "Button Mapping",
	"111": "Exit",
	"112": "SAVE AND EXIT",
	"113": "%dm later",
	"114": "Never",
	"115": "Hibernate",
	"116": "Delete ROM",
	"117": "Delete ROM from this list?",
	"118": "Color",
	"119": "Brightness",
	"120": "Tint",
	"121": "Saturation",
	"122": "Contrast",
	"123": "Restart to apply changes",
	"124": "Apply Changes",
	"125": "Theme",
	"126": "Font size",
	"127": "Default",
	"128": "Delete",
	"129": "Audio repair",
	"130": "Repair",
	"131": "WIFI",
	"132": "ACTIVITY",
	"133": "Connect",
	"134": "Hotspot",
	"135": "SSID",
	"136": "Password",
	"137": "Bluetooth",
	"138": "Netplay",
	"139": "Reset Bluetooth service",
	"140": "Scanning",
	"141": "No device found",
	"142": "Bluetooth not ready",
	"143": "Place roms in the following directory",
	"144": "Reset Bluetooth",
	"145": "Hotspot on",
	"146": "CPU Frequency",
	"147": "Connected",
	"148": "My device",
	"149": "Another device",
	"150": "Info",
	"151": "Enter SSID",
	"152": "Enter password",
	"153": "Search",
	"154": "Connection error\nCheck your password\nOr restart the router",
	"155": "Website",
	"300": "Next",
	"301": "Resume"
```

</details>

2023-09-20 05:17 UTC, Aemiii91 requested changes

2023-09-20 05:17 UTC, Aemiii91 commented on static/build/miyoo/app/lang/ca.lang
> +	"lang": "Català",
This needs to be: `Català (Catalan)`

2023-09-20 12:21 UTC, Aemiii91 approved these changes

2023-09-20 12:34 UTC, merged