fix: PlayActivityUI to use most recent img for game
OnionUI/Onion pull request #1305
Opened 2023-12-06 05:29 UTC by theUnBurn

Instead of relying on a db to keep images up-to-date, we instead just grab it from where they ought to live from the scraper. This ensures the most up-to-date images for our games.

2023-12-14 18:29 UTC, schmurtzm commented
Hi, thank you for this PR, can you freed strdup please ?

2023-12-21 03:09 UTC, theUnBurn commented
Sorry for the delay @schmurtzm , but think I did what you asked. Let me know if there's anything else you want from this PR!

2024-05-09 20:03 UTC, Aemiii91 requested changes

2024-05-09 20:03 UTC, Aemiii91 commented on src/playActivity/playActivityDB.h
> +    char *rom_path = str_replace(rom_file, basename(rom_file), "");
This doesn't work with roms in subfolders.

2024-06-23 18:08 UTC, Aemiii91 approved these changes

2024-06-23 18:08 UTC, merged