CHORE:  a better gitignore  file for ignore  no extension binary files correctly
OnionUI/Onion pull request #1355
Opened 2024-01-02 15:13 UTC by codeudan

Currently, gitignore file is kind of redundant for ignore binary files and some Clang build stuff.

This is a better ignore file to ignore no extension binary files in src dir 😄

2024-01-02 15:54 UTC, Aemiii91 approved these changes
Neat :)

2024-01-03 06:20 UTC, Aemiii91 approved these changes

2024-01-03 12:41 UTC, codeudan commented
Fixed some problems.  Now can merge it.

2024-01-03 16:04 UTC, Aemiii91 commented
How does this handle `Makefile` ?

2024-05-09 20:15 UTC, Aemiii91 requested changes

2024-05-09 20:15 UTC, Aemiii91 commented on .gitignore
> +!src/*.*
Please add `!Makefile` and `!easter4`.

2024-05-09 20:15 UTC, Aemiii91 commented on .gitignore
> +src/**/*.exe
Why would we have `.exe` files?

2024-06-23 18:36 UTC, Aemiii91 commented
Closed as inactive

2024-06-23 18:36 UTC, closed without merging