FIX: format release date and size info of new version zip
OnionUI/Onion pull request #1375
Opened 2024-01-14 10:51 UTC by codeudan

2024-01-14 11:40 UTC, Aemiii91 requested changes

2024-01-14 11:40 UTC, Aemiii91 commented on static/build/.tmp_update/script/ota_update.sh
> +	sh $sysdir/script/ota_bootstrap.sh
Please revert this change.

2024-01-14 11:46 UTC, codeudan commented on static/build/.tmp_update/script/ota_update.sh
> +	sh $sysdir/script/ota_bootstrap.sh
done

2024-01-23 20:20 UTC, Aemiii91 approved these changes

2024-01-23 20:40 UTC, merged