Update index.md
OnionUI/Onion pull request #1578
Opened 2024-05-07 20:28 UTC by ikem-krueger

2024-05-07 20:58 UTC, Aemiii91 commented
Not sure I'm a fan of the backticks 🤔

2024-05-08 10:11 UTC, ikem-krueger commented
I tried to be consistent here.

2024-05-08 12:19 UTC, Aemiii91 commented
Ah, I see, we are a bit inconsistent! How about we **bold** for names? I would prefer to use backticks/code only for `user input` and such.

2024-05-08 22:40 UTC, ikem-krueger commented
I think that should be fine.

2024-05-09 20:55 UTC, Aemiii91 requested changes
Please change the formatting of names to **bold** instead of `code`.

Note: `code` formatting should be reserved for user input and alike.

2024-05-19 22:43 UTC, ikem-krueger commented
I changed the formatting to bold.

2024-05-20 21:02 UTC, Aemiii91 requested changes
This is looking really good! Just had that one minor detail - then it's perfect 😁👌

2024-05-20 21:02 UTC, Aemiii91 commented on website/docs/01-features/index.md
> +- Share your playtimes by taking a screenshot (press <kbd>MENU</kbd>+<kbd>POWER</kbd> - screenshot is saved in **Screenshots** folder).
I do think we should keep the backticks here, since `Screenshots` is actually a directory path (user input).

2024-05-21 20:30 UTC, ikem-krueger commented
Fixed it.

2024-05-21 20:48 UTC, Aemiii91 approved these changes

2024-05-21 20:58 UTC, merged

2024-05-21 22:02 UTC, Aemiii91 commented
Thank you 😊