gameSwitcher go back in simple buffering
OnionUI/Onion pull request #54
Opened 2022-08-14 20:38 UTC by schmurtzm

- gameSwitcher go back in simple buffering
- pacman doesn't select the next item automatically after a modification

2022-08-15 17:15 UTC, introkun commented on src/packageManager/packageManager.c
> +                    // Go to next item :
Do not leave commented out code. Either remove it or keep it fixed.

2022-08-16 13:26 UTC, Aemiii91 requested changes
Remove comments

2022-08-16 13:26 UTC, Aemiii91 commented on src/packageManager/packageManager.c
> +                    //     nListPosition++;
Just remove this and we're good to go!

2022-08-16 13:48 UTC, Aemiii91 approved these changes
Nice!

2022-08-16 13:49 UTC, merged