FIX: MM showing MY354 instead of MY283
OnionUI/Onion pull request #989
Opened 2023-07-06 17:23 UTC by tGecko

Currently, the MainUI binaries for the 283 show MY354 in the Settings/About device screen.
Fixed by patching the 283-clean/283-expert binaries.
![MainUI_000](https://github.com/OnionUI/Onion/assets/6023076/577e24db-7502-4a1e-b83b-d8604b425dcd)

2023-07-06 17:24 UTC, Aemiii91 approved these changes

2023-07-06 19:44 UTC, Aemiii91 requested changes

2023-07-06 19:44 UTC, Aemiii91 commented on static/build/.tmp_update/runtime.sh
> -deviceModel=0
This is better to leave, to denote it as a global variable

2023-07-06 19:44 UTC, Aemiii91 commented on static/build/.tmp_update/runtime.sh
> +    mount_main_ui
I think you should unmount it first. Maybe we should actually keep the expert/clean flag, and only remount if that changes (then move the first mount into main)

2023-07-07 04:22 UTC, tGecko commented
wow you've left no stone unturned 😁

2023-07-07 18:58 UTC, Aemiii91 approved these changes

2023-07-07 19:42 UTC, merged